module.exports = {
    EVENTS: {
        CONNECTION: 'connection',
        DISCONNECT: 'disconnect',
        SET_NICKNAME: 'setNickname',
        BECOME_ADMIN: 'becomeAdmin',
        START_GAME: 'startGame',
        SUBMIT_WHITE_CARDS: 'submitWhiteCards',
        SET_SCORE_LIMIT: 'setScoreLimit',
        SELECT_WINNER: 'selectWinner',
        START_NEW_ROUND: 'startNewRound',
        UPDATE_USER_LIST: 'updateUserList',
        UPDATE_HOST: 'updateHost',
        ADMIN_SET: 'adminSet',
        ADMIN_RESET: 'adminReset',
        ERROR_MESSAGE: 'errorMessage',
        GAME_STARTED: 'gameStarted',
        UPDATE_HAND: 'updateHand',
        UPDATE_SCORE_LIMIT: 'updateScoreLimit',
        ALL_CARDS_SUBMITTED: 'allCardsSubmitted',
        WINNER_SELECTED: 'winnerSelected',
        ANNOUNCE_TOP_PLAYERS: 'announceTopPlayers',
        NEXT_ROUND: 'nextRound',
        PLAYER_SUBMITTED_CARDS: 'playerSubmittedCards',
    },
};
